const habitIcons = [
  {
    id: 11,
    iconCode: "achievement",
    iconUrl: "achievement.png",
    iconAlt: "Achievement",
    iconName: "Achievement",
  },
  {
    id: 12,
    iconCode: "advantage",
    iconUrl: "advantage.png",
    iconAlt: "Advantage",
    iconName: "Advantage",
  },
  {
    id: 13,
    iconCode: "aspirating",
    iconUrl: "aspirating.png",
    iconAlt: "Aspirating",
    iconName: "Aspirating",
  },
  {
    id: 14,
    iconCode: "attitude",
    iconUrl: "attitude.png",
    iconAlt: "Attitude",
    iconName: "Attitude",
  },
  {
    id: 15,
    iconCode: "bad-habit",
    iconUrl: "bad-habit.png",
    iconAlt: "Bad habit",
    iconName: "Bad habit",
  },
  {
    id: 16,
    iconCode: "career",
    iconUrl: "career.png",
    iconAlt: "Career",
    iconName: "Career",
  },
  {
    id: 17,
    iconCode: "challenge",
    iconUrl: "challenge.png",
    iconAlt: "Challenge",
    iconName: "Challenge",
  },
  {
    id: 18,
    iconCode: "collaborate",
    iconUrl: "collaborate.png",
    iconAlt: "Collaborate",
    iconName: "Collaborate",
  },
  {
    id: 19,
    iconCode: "comfort-zone",
    iconUrl: "comfort-zone.png",
    iconAlt: "Comfort zone",
    iconName: "Comfort zone",
  },
  {
    id: 20,
    iconCode: "comfort",
    iconUrl: "comfort.png",
    iconAlt: "Comfort",
    iconName: "Comfort",
  },
  {
    id: 21,
    iconCode: "communiations",
    iconUrl: "communiations.png",
    iconAlt: "Communiations",
    iconName: "Communiations",
  },
  {
    id: 22,
    iconCode: "concentrate",
    iconUrl: "concentrate.png",
    iconAlt: "Concentrate",
    iconName: "Concentrate",
  },
  {
    id: 23,
    iconCode: "confidence",
    iconUrl: "confidence.png",
    iconAlt: "Confidence",
    iconName: "Confidence",
  },
  {
    id: 24,
    iconCode: "courage",
    iconUrl: "courage.png",
    iconAlt: "Courage",
    iconName: "Courage",
  },
  {
    id: 25,
    iconCode: "creativity",
    iconUrl: "creativity.png",
    iconAlt: "Creativity",
    iconName: "Creativity",
  },
  {
    id: 26,
    iconCode: "decision-making",
    iconUrl: "decision-making.png",
    iconAlt: "Decision making",
    iconName: "Decision making",
  },
  {
    id: 27,
    iconCode: "decreasing",
    iconUrl: "decreasing.png",
    iconAlt: "Decreasing",
    iconName: "Decreasing",
  },
  {
    id: 28,
    iconCode: "determine",
    iconUrl: "determine.png",
    iconAlt: "Determine",
    iconName: "Determine",
  },
  {
    id: 29,
    iconCode: "development-plan",
    iconUrl: "development-plan.png",
    iconAlt: "Development plan",
    iconName: "Development plan",
  },
  {
    id: 30,
    iconCode: "disadvantage",
    iconUrl: "disadvantage.png",
    iconAlt: "Disadvantage",
    iconName: "Disadvantage",
  },
  {
    id: 31,
    iconCode: "dreams",
    iconUrl: "dreams.png",
    iconAlt: "Dreams",
    iconName: "Dreams",
  },
  {
    id: 32,
    iconCode: "education",
    iconUrl: "education.png",
    iconAlt: "Education",
    iconName: "Education",
  },
  {
    id: 33,
    iconCode: "effective",
    iconUrl: "effective.png",
    iconAlt: "Effective",
    iconName: "Effective",
  },
  {
    id: 34,
    iconCode: "emotional-intelligence",
    iconUrl: "emotional-intelligence.png",
    iconAlt: "Emotional intelligence",
    iconName: "Emotional intelligence",
  },
  {
    id: 35,
    iconCode: "empathetic",
    iconUrl: "empathetic.png",
    iconAlt: "Empathetic",
    iconName: "Empathetic",
  },
  {
    id: 36,
    iconCode: "evolution",
    iconUrl: "evolution.png",
    iconAlt: "Evolution",
    iconName: "Evolution",
  },
  {
    id: 37,
    iconCode: "exercise",
    iconUrl: "exercise.png",
    iconAlt: "Exercise",
    iconName: "Exercise",
  },
  {
    id: 38,
    iconCode: "feedback",
    iconUrl: "feedback.png",
    iconAlt: "Feedback",
    iconName: "Feedback",
  },
  {
    id: 39,
    iconCode: "goals",
    iconUrl: "goals.png",
    iconAlt: "Goals",
    iconName: "Goals",
  },
  {
    id: 40,
    iconCode: "good-attitude",
    iconUrl: "good-attitude.png",
    iconAlt: "Good attitude",
    iconName: "Good attitude",
  },
  {
    id: 41,
    iconCode: "gratitude",
    iconUrl: "gratitude.png",
    iconAlt: "Gratitude",
    iconName: "Gratitude",
  },
  {
    id: 42,
    iconCode: "habits",
    iconUrl: "habits.png",
    iconAlt: "Habits",
    iconName: "Habits",
  },
  {
    id: 43,
    iconCode: "health",
    iconUrl: "health.png",
    iconAlt: "Health",
    iconName: "Health",
  },
  {
    id: 44,
    iconCode: "healthy-eating",
    iconUrl: "healthy-eating.png",
    iconAlt: "Healthy eating",
    iconName: "Healthy eating",
  },
  {
    id: 45,
    iconCode: "human-capital",
    iconUrl: "human-capital.png",
    iconAlt: "Human capital",
    iconName: "Human capital",
  },
  {
    id: 46,
    iconCode: "idea",
    iconUrl: "idea.png",
    iconAlt: "Idea",
    iconName: "Idea",
  },
  {
    id: 47,
    iconCode: "increase",
    iconUrl: "increase.png",
    iconAlt: "Increase",
    iconName: "Increase",
  },
  {
    id: 48,
    iconCode: "independence",
    iconUrl: "independence.png",
    iconAlt: "Independence",
    iconName: "Independence",
  },
  {
    id: 49,
    iconCode: "initiative",
    iconUrl: "initiative.png",
    iconAlt: "Initiative",
    iconName: "Initiative",
  },
  {
    id: 50,
    iconCode: "innovate",
    iconUrl: "innovate.png",
    iconAlt: "Innovate",
    iconName: "Innovate",
  },
  {
    id: 51,
    iconCode: "inspire",
    iconUrl: "inspire.png",
    iconAlt: "Inspire",
    iconName: "Inspire",
  },
  {
    id: 52,
    iconCode: "kind",
    iconUrl: "kind.png",
    iconAlt: "Kind",
    iconName: "Kind",
  },
  {
    id: 53,
    iconCode: "knowledge",
    iconUrl: "knowledge.png",
    iconAlt: "Knowledge",
    iconName: "Knowledge",
  },
  {
    id: 54,
    iconCode: "leadership",
    iconUrl: "leadership.png",
    iconAlt: "Leadership",
    iconName: "Leadership",
  },
  {
    id: 55,
    iconCode: "learning",
    iconUrl: "learning.png",
    iconAlt: "Learning",
    iconName: "Learning",
  },
  {
    id: 56,
    iconCode: "lifestyle",
    iconUrl: "lifestyle.png",
    iconAlt: "Lifestyle",
    iconName: "Lifestyle",
  },
  {
    id: 57,
    iconCode: "meditate",
    iconUrl: "meditate.png",
    iconAlt: "Meditate",
    iconName: "Meditate",
  },
  {
    id: 58,
    iconCode: "mental-health",
    iconUrl: "mental-health.png",
    iconAlt: "Mental health",
    iconName: "Mental health",
  },
  {
    id: 59,
    iconCode: "mindset",
    iconUrl: "mindset.png",
    iconAlt: "Mindset",
    iconName: "Mindset",
  },
  {
    id: 60,
    iconCode: "motivate",
    iconUrl: "motivate.png",
    iconAlt: "Motivate",
    iconName: "Motivate",
  },
  {
    id: 61,
    iconCode: "negative-thinking",
    iconUrl: "negative-thinking.png",
    iconAlt: "Negative thinking",
    iconName: "Negative thinking",
  },
  {
    id: 62,
    iconCode: "open-mind",
    iconUrl: "open-mind.png",
    iconAlt: "Open mind",
    iconName: "Open mind",
  },
  {
    id: 63,
    iconCode: "overcoming",
    iconUrl: "overcoming.png",
    iconAlt: "Overcoming",
    iconName: "Overcoming",
  },
  {
    id: 64,
    iconCode: "passion",
    iconUrl: "passion.png",
    iconAlt: "Passion",
    iconName: "Passion",
  },
  {
    id: 65,
    iconCode: "performance",
    iconUrl: "performance.png",
    iconAlt: "Performance",
    iconName: "Performance",
  },
  {
    id: 66,
    iconCode: "personal-growth",
    iconUrl: "personal-growth.png",
    iconAlt: "Personal growth",
    iconName: "Personal growth",
  },
  {
    id: 67,
    iconCode: "positive-attitude",
    iconUrl: "positive-attitude.png",
    iconAlt: "Positive attitude",
    iconName: "Positive attitude",
  },
  {
    id: 68,
    iconCode: "potential",
    iconUrl: "potential.png",
    iconAlt: "Potential",
    iconName: "Potential",
  },
  {
    id: 69,
    iconCode: "productive",
    iconUrl: "productive.png",
    iconAlt: "Productive",
    iconName: "Productive",
  },
  {
    id: 70,
    iconCode: "progress",
    iconUrl: "progress.png",
    iconAlt: "Progress",
    iconName: "Progress",
  },
  {
    id: 71,
    iconCode: "quality-of-life",
    iconUrl: "quality-of-life.png",
    iconAlt: "Quality of life",
    iconName: "Quality of life",
  },
  {
    id: 72,
    iconCode: "relationships",
    iconUrl: "relationships.png",
    iconAlt: "Relationships",
    iconName: "Relationships",
  },
  {
    id: 73,
    iconCode: "risk",
    iconUrl: "risk.png",
    iconAlt: "Risk",
    iconName: "Risk",
  },
  {
    id: 74,
    iconCode: "routine",
    iconUrl: "routine.png",
    iconAlt: "Routine",
    iconName: "Routine",
  },
  {
    id: 75,
    iconCode: "self-awareness_1",
    iconUrl: "self-awareness_1.png",
    iconAlt: "Self awareness",
    iconName: "Self awareness",
  },
  {
    id: 76,
    iconCode: "self-awareness_2",
    iconUrl: "self-awareness_2.png",
    iconAlt: "Self awareness",
    iconName: "Self awareness",
  },
  {
    id: 77,
    iconCode: "self-esteem",
    iconUrl: "self-esteem.png",
    iconAlt: "Self esteem",
    iconName: "Self esteem",
  },
  {
    id: 78,
    iconCode: "self-improvement",
    iconUrl: "self-improvement.png",
    iconAlt: "Self improvement",
    iconName: "Self improvement",
  },
  {
    id: 79,
    iconCode: "self-knowledge",
    iconUrl: "self-knowledge.png",
    iconAlt: "Self knowledge",
    iconName: "Self knowledge",
  },
  {
    id: 80,
    iconCode: "skills",
    iconUrl: "skills.png",
    iconAlt: "Skills",
    iconName: "Skills",
  },
  {
    id: 81,
    iconCode: "sleeping",
    iconUrl: "sleeping.png",
    iconAlt: "Sleeping",
    iconName: "Sleeping",
  },
  {
    id: 82,
    iconCode: "social-status",
    iconUrl: "social-status.png",
    iconAlt: "Social status",
    iconName: "Social status",
  },
  {
    id: 83,
    iconCode: "spiritual",
    iconUrl: "spiritual.png",
    iconAlt: "Spiritual",
    iconName: "Spiritual",
  },
  {
    id: 84,
    iconCode: "standards",
    iconUrl: "standards.png",
    iconAlt: "Standards",
    iconName: "Standards",
  },
  {
    id: 85,
    iconCode: "status",
    iconUrl: "status.png",
    iconAlt: "Status",
    iconName: "Status",
  },
  {
    id: 86,
    iconCode: "strategic",
    iconUrl: "strategic.png",
    iconAlt: "Strategic",
    iconName: "Strategic",
  },
  {
    id: 87,
    iconCode: "stress-management",
    iconUrl: "stress-management.png",
    iconAlt: "Stress management",
    iconName: "Stress management",
  },
  {
    id: 88,
    iconCode: "talent",
    iconUrl: "talent.png",
    iconAlt: "Talent",
    iconName: "Talent",
  },
  {
    id: 89,
    iconCode: "time-management",
    iconUrl: "time-management.png",
    iconAlt: "Time management",
    iconName: "Time management",
  },
  {
    id: 90,
    iconCode: "training",
    iconUrl: "training.png",
    iconAlt: "Training",
    iconName: "Training",
  },
  {
    id: 91,
    iconCode: "values",
    iconUrl: "values.png",
    iconAlt: "Values",
    iconName: "Values",
  },
  {
    id: 92,
    iconCode: "vision",
    iconUrl: "vision.png",
    iconAlt: "Vision",
    iconName: "Vision",
  },
  {
    id: 93,
    iconCode: "wealth",
    iconUrl: "wealth.png",
    iconAlt: "Wealth",
    iconName: "Wealth",
  },
  {
    id: 94,
    iconCode: "willpower",
    iconUrl: "willpower.png",
    iconAlt: "Willpower",
    iconName: "Willpower",
  },
  {
    id: 95,
    iconCode: "work-life",
    iconUrl: "work-life.png",
    iconAlt: "Work life",
    iconName: "Work life",
  },
];

export default habitIcons;

export type HabitIcons = typeof habitIcons;
